CXX = g++
CXXFLAGS = -std=c++11

TARGET = floating_point_comparison

$(TARGET): floating_point_comparison.cc
	$(CXX) $(CXXFLAGS) -o $(TARGET) floating_point_comparison.cc

.PHONY: clean
clean:
	rm -f $(TARGET)

